namespace ContactBook;

using System.Collections.Generic;

public static class ContactSeed
{
    
   public static List<Contact.Contact> Contacts = new List<Contact.Contact>
{
    new Contact.Contact("Juan","Perez","7871234567","juan.perez@gmail.com"),
    new Contact.Contact("Maria","Lopez","3055551234","maria.lopez@yahoo.com"),
    new Contact.Contact("Carlos","Diaz","2129876543","carlosd@hotmail.com"),
    new Contact.Contact("Ana","Torres","4073332211","ana.torres@outlook.com"),
    new Contact.Contact("Luis","Rivera","6461112222",""),
    new Contact.Contact("Sofia","Gomez","","sofia.gomez@gmail.com"),
    new Contact.Contact("Miguel","Santos","9394445555","miguel@icloud.com"),
    new Contact.Contact("Laura","Vega","",""),
    new Contact.Contact("Pedro","Ortiz","7188889999","pedro.ortiz@yahoo.com"),
    new Contact.Contact("Elena","Cruz","6177778888","elena@protonmail.com"),

    new Contact.Contact("Jose","Martinez","2134567890","jose.m@gmail.com"),
    new Contact.Contact("Lucia","Castro","","lucia.castro@hotmail.com"),
    new Contact.Contact("Andres","Morales","9173334444",""),
    new Contact.Contact("Valeria","Ramos","3232221111","valeria@outlook.com"),
    new Contact.Contact("Diego","Flores","",""),
    new Contact.Contact("Paula","Reyes","8089998888","paula@yahoo.com"),
    new Contact.Contact("Ricardo","Navarro","7021110000","ricardo@gmail.com"),
    new Contact.Contact("Daniela","Mendez","","daniela@icloud.com"),
    new Contact.Contact("Fernando","Silva","5123336666",""),
    new Contact.Contact("Camila","Herrera","9154443333","camila@protonmail.com"),

    new Contact.Contact("Jorge","Alvarez","3051119999","jorge@hotmail.com"),
    new Contact.Contact("Natalia","Fuentes","","natalia@gmail.com"),
    new Contact.Contact("Hector","Pena","7865552222",""),
    new Contact.Contact("Isabel","Suarez","3478887777","isabel@yahoo.com"),
    new Contact.Contact("Adrian","Salazar","",""),
    new Contact.Contact("Gabriela","Romero","2133337777","gabriela@outlook.com"),
    new Contact.Contact("Oscar","Campos","6462225555",""),
    new Contact.Contact("Patricia","Nunez","","patricia@gmail.com"),
    new Contact.Contact("Rafael","Delgado","2127776666","rafael@yahoo.com"),
    new Contact.Contact("Monica","Ibarra","",""),

    new Contact.Contact("Victor","Acosta","7878881111","victor@gmail.com"),
    new Contact.Contact("Andrea","Espinoza","","andrea@hotmail.com"),
    new Contact.Contact("Eduardo","Cabrera","9392229999",""),
    new Contact.Contact("Silvia","Valdez","3056663333","silvia@yahoo.com"),
    new Contact.Contact("Manuel","Quintero","",""),
    new Contact.Contact("Claudia","Bravo","4075554444","claudia@outlook.com"),
    new Contact.Contact("Ivan","Mejia","9172221111",""),
    new Contact.Contact("Veronica","Carrillo","","veronica@gmail.com"),
    new Contact.Contact("Julio","Rios","3234445555","julio@yahoo.com"),
    new Contact.Contact("Teresa","Vargas","",""),

    new Contact.Contact("Alberto","Montoya","7029990000","alberto@gmail.com"),
    new Contact.Contact("Rosa","Soto","","rosa@hotmail.com"),
    new Contact.Contact("Mario","Ortega","5121112222",""),
    new Contact.Contact("Angela","Pizarro","9158887777","angela@yahoo.com"),
    new Contact.Contact("Pablo","Escobar","",""),
    new Contact.Contact("Carmen","Rivas","7182223333","carmen@outlook.com"),
    new Contact.Contact("Ruben","Galvez","6469991111",""),
    new Contact.Contact("Luz","Peralta","","luz@gmail.com"),
    new Contact.Contact("Esteban","Contreras","2123334444","esteban@yahoo.com"),
    new Contact.Contact("Gloria","Correa","",""),

    new Contact.Contact("Hugo","Aguilar","3057778888","hugo@gmail.com"),
    new Contact.Contact("Beatriz","Serrano","","beatriz@hotmail.com"),
    new Contact.Contact("Emilio","Santana","7863332222",""),
    new Contact.Contact("Olga","Molina","3471112222","olga@yahoo.com"),
    new Contact.Contact("Raul","Benitez","",""),
    new Contact.Contact("Diana","Ponce","2135556666","diana@outlook.com"),
    new Contact.Contact("Gerardo","Tapia","6467778888",""),
    new Contact.Contact("Marina","Villanueva","","marina@gmail.com"),
    new Contact.Contact("Sergio","Rosales","2121113333","sergio@yahoo.com"),
    new Contact.Contact("Norma","Cortes","",""),

    new Contact.Contact("Cristian","Padilla","7874448888","cristian@gmail.com"),
    new Contact.Contact("Lorena","Arias","","lorena@hotmail.com"),
    new Contact.Contact("Fabian","Guerrero","9397772222",""),
    new Contact.Contact("Yolanda","Velasquez","3051114444","yolanda@yahoo.com"),
    new Contact.Contact("Samuel","Zamora","",""),
    new Contact.Contact("Karina","Figueroa","4073338888","karina@outlook.com"),
    new Contact.Contact("Bruno","Luna","9174442222",""),
    new Contact.Contact("Rocio","Chavez","","rocio@gmail.com"),
    new Contact.Contact("Elias","Campos","3239998888","elias@yahoo.com"),
    new Contact.Contact("Marta","Cano","",""),

    new Contact.Contact("Sebastian","Arroyo","7871230000","sebastian@gmail.com"),
    new Contact.Contact("Alexa","Morin","","alexa@hotmail.com"),
    new Contact.Contact("Kevin","Ruiz","9390001111",""),
    new Contact.Contact("Paola","Jimenez","3058882222","paola@yahoo.com"),
    new Contact.Contact("Javier","Ochoa","",""),
    new Contact.Contact("Daniel","Mora","4077776666","daniel@outlook.com"),
    new Contact.Contact("Nicole","Lara","9178880000",""),
    new Contact.Contact("Tatiana","Guerra","","tatiana@gmail.com"),
    new Contact.Contact("Aaron","Solis","3232229999","aaron@yahoo.com"),
    new Contact.Contact("Jessica","Bermudez","",""),

    new Contact.Contact("Luis","Castillo","7023331111","luis@gmail.com"),
    new Contact.Contact("Carla","Montes","","carla@hotmail.com"),
    new Contact.Contact("Noel","Velazquez","5128887777",""),
    new Contact.Contact("Melissa","Salinas","9150002222","melissa@yahoo.com"),
    new Contact.Contact("Omar","Zuniga","",""),
    new Contact.Contact("Vanessa","Paredes","7185558888","vanessa@outlook.com"),
    new Contact.Contact("Erick","Rangel","6463331111",""),
    new Contact.Contact("Paola","Navarrete","","paola@gmail.com"),
    new Contact.Contact("Guillermo","Cedeno","2129994444","guillermo@yahoo.com"),
    new Contact.Contact("Yadira","Reyes","","")
};
}